artifact_uri: file:///Users/rosalie/Documents/DataExplorationProject/Abgabe_DataExplorationProject/mlruns/0/aba2f65e8af64d1285435da64e75fb84/artifacts
end_time: 1682440873156
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: aba2f65e8af64d1285435da64e75fb84
run_name: persistent-skink-898
run_uuid: aba2f65e8af64d1285435da64e75fb84
source_name: ''
source_type: 4
source_version: ''
start_time: 1682440865524
status: 3
tags: []
user_id: rosalie
