artifact_uri: file:///Users/rosalie/Documents/DataExplorationProject/Abgabe_DataExplorationProject/mlruns/0/b9a1faf3f0344bcfa03f54168a3b45f1/artifacts
end_time: 1682440841822
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b9a1faf3f0344bcfa03f54168a3b45f1
run_name: adaptable-goose-418
run_uuid: b9a1faf3f0344bcfa03f54168a3b45f1
source_name: ''
source_type: 4
source_version: ''
start_time: 1682440833646
status: 3
tags: []
user_id: rosalie
