artifact_location: file:///Users/rosalie/Documents/DataExplorationProject/Abgabe_DataExplorationProject/mlruns/0
creation_time: 1681893917424
experiment_id: '0'
last_update_time: 1681893917424
lifecycle_stage: active
name: Default
